# Generated by Django 2.2.3 on 2019-07-15 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
